import { BlocksMetadata, categoryIds } from "./declarations";

export const blocksMetadata: BlocksMetadata[] = [
  {
    id: "file-upload-01",
    category: categoryIds.FileUpload,
    name: "File Upload with Preview",
    iframeHeight: "506px",
    type: "directory",
  },
  {
    id: "file-upload-02",
    category: categoryIds.FileUpload,
    name: "File Upload Simple",
    iframeHeight: "460px",
    type: "file",
  },
  {
    id: "file-upload-03",
    category: categoryIds.FileUpload,
    name: "File Upload Multi-File Dropzone",
    iframeHeight: "685px",
    type: "file",
  },
  {
    id: "file-upload-04",
    category: categoryIds.FileUpload,
    name: "File Upload Drag & Drop",
    iframeHeight: "550px",
    type: "file",
  },
  {
    id: "file-upload-05",
    category: categoryIds.FileUpload,
    name: "File Upload with Progress",
    iframeHeight: "430px",
    type: "file",
  },
  {
    id: "file-upload-06",
    category: categoryIds.FileUpload,
    name: "File Upload with Status Sections",
    iframeHeight: "800px",
    type: "file",
  },

  {
    id: "form-layout-01",
    category: categoryIds.FormLayout,
    name: "Form with Workspace Fields",
    iframeHeight: "585px",
    type: "file",
  },
  {
    id: "form-layout-02",
    category: categoryIds.FormLayout,
    name: "Form with Side Labels",
    iframeHeight: "920px",
    type: "file",
  },
  {
    id: "form-layout-03",
    category: categoryIds.FormLayout,
    name: "Form with Checkbox Settings",
    iframeHeight: "1060px",
    type: "file",
  },
  {
    id: "form-layout-04",
    category: categoryIds.FormLayout,
    name: "Form with Package Selection",
    iframeHeight: "800px",
    type: "file",
  },
  {
    id: "form-layout-05",
    category: categoryIds.FormLayout,
    name: "Form with Plan Selection",
    iframeHeight: "1240px",
    type: "file",
  },

  {
    id: "login-01",
    category: categoryIds.Login,
    name: "Login with Email and Google",
    iframeHeight: "400px",
    type: "file",
  },
  {
    id: "login-02",
    category: categoryIds.Login,
    name: "Login with Email, Password and Google",
    iframeHeight: "500px",
    type: "file",
  },
  {
    id: "login-03",
    category: categoryIds.Login,
    name: "Login with Email and Password",
    iframeHeight: "420px",
    type: "file",
  },
  {
    id: "login-04",
    category: categoryIds.Login,
    name: "Login with Social Buttons",
    iframeHeight: "620px",
    type: "file",
  },
  {
    id: "login-05",
    category: categoryIds.Login,
    name: "Login Card Signup Form",
    iframeHeight: "750px",
    type: "file",
  },
  {
    id: "login-06",
    category: categoryIds.Login,
    name: "Login with Magic Link and SSO",
    iframeHeight: "700px",
    type: "file",
  },
  {
    id: "login-07",
    category: categoryIds.Login,
    name: "Login Full Page with Icons",
    iframeHeight: "700px",
    type: "file",
  },
  {
    id: "login-08",
    category: categoryIds.Login,
    name: "Login with SSO",
    iframeHeight: "680px",
    type: "file",
  },
  {
    id: "login-09",
    category: categoryIds.Login,
    name: "Login Signup with Role Selection",
    iframeHeight: "880px",
    type: "file",
  },

  {
    id: "stats-01",
    category: categoryIds.Stats,
    name: "Stats with Trending",
    iframeHeight: "200px",
    type: "file",
  },
  {
    id: "stats-02",
    category: categoryIds.Stats,
    name: "Stats with Borders",
    iframeHeight: "200px",
    type: "file",
  },
  {
    id: "stats-03",
    category: categoryIds.Stats,
    name: "Stats with Card Layout",
    iframeHeight: "220px",
    type: "file",
  },
  {
    id: "stats-04",
    category: categoryIds.Stats,
    name: "Stats with Badges",
    iframeHeight: "200px",
    type: "file",
  },
  {
    id: "stats-05",
    category: categoryIds.Stats,
    name: "Stats with Links",
    iframeHeight: "240px",
    type: "file",
  },
  {
    id: "stats-06",
    category: categoryIds.Stats,
    name: "Stats with Status",
    iframeHeight: "270px",
    type: "file",
  },
  {
    id: "stats-07",
    category: categoryIds.Stats,
    name: "Stats with Circular Progress",
    iframeHeight: "280px",
    type: "file",
  },
  {
    id: "stats-08",
    category: categoryIds.Stats,
    name: "Stats with Circular Progress and Links",
    iframeHeight: "240px",
    type: "file",
  },
  {
    id: "stats-09",
    category: categoryIds.Stats,
    name: "Stats with Progress",
    iframeHeight: "230px",
    type: "file",
  },
  {
    id: "stats-10",
    category: categoryIds.Stats,
    name: "Stats with Area Chart",
    iframeHeight: "220px",
    type: "file",
  },
  {
    id: "stats-11",
    category: categoryIds.Stats,
    name: "Stats Dashboard with Progress Bars",
    iframeHeight: "280px",
    type: "file",
  },
  {
    id: "stats-12",
    category: categoryIds.Stats,
    name: "Stats Usage Dashboard",
    iframeHeight: "700px",
    type: "file",
  },
  {
    id: "stats-13",
    category: categoryIds.Stats,
    name: "Stats with Segmented Progress",
    iframeHeight: "250px",
    type: "file",
  },
  {
    id: "stats-14",
    category: categoryIds.Stats,
    name: "Stats with Usage Breakdown",
    iframeHeight: "400px",
    type: "file",
  },
  {
    id: "stats-15",
    category: categoryIds.Stats,
    name: "Stats with Value Breakdown",
    iframeHeight: "280px",
    type: "file",
  },

  {
    id: "grid-list-01",
    category: categoryIds.GridList,
    name: "Grid List with Dropdown",
    iframeHeight: "200px",
    type: "file",
  },
  {
    id: "grid-list-02",
    category: categoryIds.GridList,
    name: "Grid List with Links",
    iframeHeight: "250px",
    type: "file",
  },
  {
    id: "grid-list-03",
    category: categoryIds.GridList,
    name: "Grid List with Icons",
    iframeHeight: "500px",
    type: "file",
  },

  {
    id: "command-menu-01",
    category: categoryIds.CommandMenu,
    name: "Command Menu with Groups",
    iframeHeight: "550px",
    type: "file",
  },
  {
    id: "command-menu-02",
    category: categoryIds.CommandMenu,
    name: "Command Menu with Keyboard Shortcuts",
    iframeHeight: "650px",
    type: "file",
  },
  {
    id: "command-menu-03",
    category: categoryIds.CommandMenu,
    name: "Command Menu with Documentation Search",
    iframeHeight: "550px",
    type: "file",
  },

  {
    id: "dialog-01",
    category: categoryIds.Dialogs,
    name: "Dialog Confirmation",
    iframeHeight: "350px",
    type: "file",
  },
  {
    id: "dialog-02",
    category: categoryIds.Dialogs,
    name: "Dialog with Warning Icon",
    iframeHeight: "350px",
    type: "file",
  },
  {
    id: "dialog-03",
    category: categoryIds.Dialogs,
    name: "Dialog with Input Field",
    iframeHeight: "400px",
    type: "file",
  },
  {
    id: "dialog-04",
    category: categoryIds.Dialogs,
    name: "Dialog with Two Buttons",
    iframeHeight: "350px",
    type: "file",
  },
  {
    id: "dialog-05",
    category: categoryIds.Dialogs,
    name: "Dialog with Password Confirmation",
    iframeHeight: "400px",
    type: "file",
  },
  {
    id: "dialog-06",
    category: categoryIds.Dialogs,
    name: "Dialog with Privacy Toggle",
    iframeHeight: "450px",
    type: "file",
  },
  {
    id: "dialog-07",
    category: categoryIds.Dialogs,
    name: "Dialog with Member List",
    iframeHeight: "450px",
    type: "file",
  },
  {
    id: "dialog-08",
    category: categoryIds.Dialogs,
    name: "Dialog with Email and Password Fields",
    iframeHeight: "600px",
    type: "file",
  },
  {
    id: "dialog-09",
    category: categoryIds.Dialogs,
    name: "Dialog with Link Share and Toggles",
    iframeHeight: "350px",
    type: "file",
  },
  {
    id: "dialog-10",
    category: categoryIds.Dialogs,
    name: "Dialog with Calendar and Time Picker",
    iframeHeight: "750px",
    type: "file",
  },
  {
    id: "dialog-11",
    category: categoryIds.Dialogs,
    name: "Dialog Multi-Step Wizard",
    iframeHeight: "650px",
    type: "file",
  },
  {
    id: "dialog-12",
    category: categoryIds.Dialogs,
    name: "Dialog with Avatar Upload",
    iframeHeight: "650px",
    type: "file",
  },

  {
    id: "sidebar-01",
    category: categoryIds.Sidebar,
    name: "Sidebar Collapsible Sections",
    iframeHeight: "1000px",
    type: "directory",
  },
  {
    id: "sidebar-02",
    category: categoryIds.Sidebar,
    name: "Sidebar Dashboard Inset",
    iframeHeight: "1000px",
    type: "directory",
  },
  {
    id: "sidebar-03",
    category: categoryIds.Sidebar,
    name: "Sidebar Dashboard Floating",
    iframeHeight: "1000px",
    type: "directory",
  },
  {
    id: "sidebar-04",
    category: categoryIds.Sidebar,
    name: "Sidebar Double-Sided Mail",
    iframeHeight: "1000px",
    type: "directory",
  },
  {
    id: "sidebar-05",
    category: categoryIds.Sidebar,
    name: "Sidebar Double-Sided",
    iframeHeight: "1000px",
    type: "directory",
  },
  {
    id: "sidebar-06",
    category: categoryIds.Sidebar,
    name: "Sidebar Replacement",
    iframeHeight: "1000px",
    type: "directory",
  },

  {
    id: "ai-01",
    category: categoryIds.AI,
    name: "AI Chat with Voice Input",
    iframeHeight: "450px",
    type: "file",
  },
  {
    id: "ai-02",
    category: categoryIds.AI,
    name: "AI Chat with Model Selection",
    iframeHeight: "400px",
    type: "file",
  },
  {
    id: "ai-03",
    category: categoryIds.AI,
    name: "AI Chat Compact Interface",
    iframeHeight: "350px",
    type: "file",
  },
  {
    id: "ai-04",
    category: categoryIds.AI,
    name: "AI Chat with File Attachments",
    iframeHeight: "650px",
    type: "file",
  },

  {
    id: "table-01",
    category: categoryIds.Tables,
    name: "Table with Accordion",
    iframeHeight: "800px",
    type: "file",
  },
  {
    id: "table-02",
    category: categoryIds.Tables,
    name: "Table with Actions",
    iframeHeight: "600px",
    type: "file",
  },
  {
    id: "table-03",
    category: categoryIds.Tables,
    name: "Table with Filters",
    iframeHeight: "700px",
    type: "file",
  },
  {
    id: "table-04",
    category: categoryIds.Tables,
    name: "Table with Grouped Rows",
    iframeHeight: "600px",
    type: "file",
  },
  {
    id: "table-05",
    category: categoryIds.Tables,
    name: "Data Table",
    iframeHeight: "600px",
    type: "file",
  },

  {
    id: "onboarding-01",
    category: categoryIds.Onboarding,
    name: "Onboarding",
    iframeHeight: "700px",
    type: "file",
  },
];
