/**
 * Point d'entrée centralisé pour tous les types TypeScript
 *
 * Usage:
 * import type { Product, ApiResponse, FetchProductsParams } from '@/types';
 */

// Types communs
export type {
  UUID,
  ISODateString,
  Nullable,
  Optional,
  PaginationParams,
  PaginatedResponse,
  DateRangeFilter,
  ApiResponse,
  ApiError,
  Status,
  Severity,
  SortOrder,
  SortParams,
  SearchParams,
  Entity,
  FilterValue,
  Filters,
  SelectOption,
  Metric,
  Alert,
  AsyncState,
  EventHandler,
  FormStatus,
  FormState,
  Permission,
  PermissionSet,
  DeepPartial,
  RequiredFields,
  OmitStrict,
} from './common.types';

// Modèles métier
export type {
  Product,
  Category,
  Vendor,
  MovementType,
  Movement,
  InventorySummary,
  StockLevel,
  InvoiceLine,
  Invoice,
  InvoiceImportResult,
  Ingredient,
  PlatIngredient,
  Plat,
  RestaurantSales,
  FoodCostAnalysis,
  FinanceAccount,
  FinanceCategory,
  FinanceTransaction,
  FinanceRule,
  FinanceDashboard,
  SupplierScore,
  SupplierScoreHistory,
  KPI,
  CockpitAlert,
  AuditEntry,
  User,
  AuthState,
  LoginCredentials,
  LoginResponse,
  Tenant,
} from './models.types';

// Types API
export type {
  FetchProductsParams,
  FetchProductsResponse,
  CreateProductPayload,
  UpdateProductPayload,
  FetchInventorySummaryResponse,
  SupplyPlanFilters,
  SupplyPlanItem,
  FetchSupplyPlanResponse,
  ExtractInvoiceFromTextPayload,
  ExtractInvoiceFromFilePayload,
  ExtractInvoiceResponse,
  ImportInvoicePayload,
  ImportInvoiceResponse,
  FetchInvoiceHistoryFilters,
  FetchInvoiceHistoryResponse,
  FetchRestaurantOverviewFilters,
  RestaurantOverview,
  FetchRestaurantOverviewResponse,
  FetchPlatDetailsResponse,
  SimulatePlatPricePayload,
  SimulatePlatPriceResponse,
  FetchFoodCostAnalysisFilters,
  FetchFoodCostAnalysisResponse,
  SearchFinanceTransactionsFilters,
  SearchFinanceTransactionsResponse,
  FetchFinanceAccountsFilters,
  FetchFinanceAccountsResponse,
  CreateFinanceAccountPayload,
  UpdateFinanceAccountPayload,
  FetchFinanceCategoriesFilters,
  FetchFinanceCategoriesResponse,
  CreateFinanceCategoryPayload,
  BatchCategorizeTransactionsPayload,
  ImportBankStatementsPayload,
  ImportBankStatementsResponse,
  FetchFinanceDashboardFilters,
  FetchFinanceDashboardResponse,
  FetchFinanceRulesFilters,
  FetchFinanceRulesResponse,
  CreateFinanceRulePayload,
  UpdateFinanceRulePayload,
  FetchSupplierScoreParams,
  FetchSupplierScoreResponse,
  FetchSuppliersRankingResponse,
  CompareSuppliersPayload,
  CompareSuppliersResponse,
  FetchSupplierScoreHistoryParams,
  FetchSupplierScoreHistoryResponse,
  FetchSupplierScoringOverviewResponse,
  FetchSuppliersListParams,
  FetchSuppliersListResponse,
  FetchSupplierDetailsResponse,
  RecalculateSupplierScoresPayload,
  RecalculateSupplierScoresResponse,
  FetchCockpitOverviewResponse,
  FetchCockpitAlertsFilters,
  FetchCockpitAlertsResponse,
  FetchAuditEntriesFilters,
  FetchAuditEntriesResponse,
  LoginPayload,
  LoginApiResponse,
  RegisterPayload,
  RegisterApiResponse,
  RefreshTokenResponse,
} from './api.types';
